# renew_before_expiry = 30 days
version = 2.1.0
archive_dir = /etc/letsencrypt/archive/babinskyi.ca
cert = /etc/letsencrypt/live/babinskyi.ca/cert.pem
privkey = /etc/letsencrypt/live/babinskyi.ca/privkey.pem
chain = /etc/letsencrypt/live/babinskyi.ca/chain.pem
fullchain = /etc/letsencrypt/live/babinskyi.ca/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = d2ec1eb96bfdaf96a0c89eb4876202e5
authenticator = standalone
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
